export type MediaItem = {
  type: 'image' | 'video'
  src: string
  alt: string
  caption?: string
}

export interface ArticleSection {
  heading: string
  paragraphs: string[]
  code?: { language: string; label: string; snippet: string }
  bullets?: string[]
  media?: MediaItem | MediaItem[]
}

export interface ProjectArticle {
  slug: string
  readingTime: string
  intro: string
  sections: ArticleSection[]
  lessons: string[]
  future: string[]
}

export const projectArticles: Record<string, ProjectArticle> = {
  'os-kernel': {
    slug: 'os-kernel',
    readingTime: '10 min read',
    intro: 'MyOS is a hobbyist i386 multiboot operating system whose public repository contains the kernel, a custom C library, GUI support, user applications, build scripts, disk images, and ISO packaging. The project is best understood as a complete workspace: hardware-facing kernel code and user-facing programs are developed together and staged into one bootable system.',
    sections: [
      {
        heading: 'A monolithic i386 kernel',
        paragraphs: ['The architecture-specific kernel tree contains boot and context-switch assembly alongside C implementations for the GDT, interrupts, exceptions, paging, timers, keyboard and mouse input, ATA storage, AC97 audio, graphics, and system calls. The source layout makes the machine boundary explicit: assembly handles transitions that depend on processor state, while C owns most services and drivers.', 'The kernel is monolithic rather than microkernel-based. Device support, filesystems, graphics, the desktop, and process-facing services live in one address space. For a learning OS, that keeps control flow traceable while still exposing the dependencies between subsystems.'],
        media: { type: 'video', src: '/images/OSDev/OS-Demo.mp4', alt: 'MyOS booting and running its graphical environment', caption: 'The repository builds a bootable i386 system for QEMU.' },
      },
      {
        heading: 'Paging, interrupts, and user mode',
        paragraphs: ['The i386 directory includes dedicated paging, IRQ, exception, syscall, context-switch, and user-mode entry code. Those files show that the project goes beyond printing to a framebuffer: it establishes the processor tables and transitions needed for protected execution and interrupt-driven hardware.', 'These boundaries are difficult because failure often happens below ordinary debugging tools. Keeping low-level transitions in focused files, and pairing them with C-side handlers, makes register conventions and ownership easier to inspect.'],
        bullets: ['GDT setup and flush routines', 'PIC/IRQ and exception entry stubs', 'Paging and user-mode transition assembly', 'Timer, keyboard, mouse, storage, audio, and display drivers'],
      },
      {
        heading: 'A custom userland and graphics stack',
        paragraphs: ['The workspace also contains a custom libc, libgui, and a user directory with command-line and graphical applications. The build embeds selected user binaries as blobs and stages shared headers and libraries through a sysroot.', 'This changes the engineering problem from “write a kernel feature” to “design an interface that another program can consume.” Shell commands, editors, games, paint tools, a mixer, and desktop modules exercise those interfaces and reveal where kernel APIs are incomplete.'],
        media: [{ type: 'image', src: '/images/OSDev/kernelshell.png', alt: 'MyOS command shell', caption: 'A custom shell exercises keyboard, terminal, and filesystem services.' }, { type: 'image', src: '/images/OSDev/snake-game.png', alt: 'Snake running in MyOS', caption: 'Bundled applications run against the project’s own runtime and GUI layers.' }],
      },
      {
        heading: 'The build is part of the system',
        paragraphs: ['Shell scripts and Makefiles coordinate an i686-elf cross-toolchain, build headers and projects into sysroot, create a GRUB-compatible ISO, and launch QEMU with configurable graphics, audio, disk, and networking options. The linker script and generated user-blob list determine what is placed into the kernel image.', 'That reproducible path matters as much as an individual driver. A low-level project is only useful when the source can be transformed into boot media with a known memory layout and tested repeatedly in an emulator.'],
        media: { type: 'image', src: '/images/OSDev/architecture.png', alt: 'MyOS architecture and build flow', caption: 'Kernel, libraries, and user programs are staged before ISO packaging.' },
      },
    ],
    lessons: ['Low-level boundaries become manageable when assembly transitions and C handlers have clear responsibilities', 'A custom libc and userland force kernel interfaces to serve real callers', 'Build scripts, linker layout, and emulator configuration are core operating-system code'],
    future: ['Document subsystem contracts and boot invariants beside the source', 'Add repeatable emulator tests for syscalls, paging, and filesystems', 'Separate generated disk and ISO artifacts from source-focused history'],
  },
  'pulse-social-platform': {
    slug: 'pulse-social-platform',
    readingTime: '9 min read',
    intro: 'Pulse combines a Flutter client with a TypeScript/Firebase backend and a separate Python recommendation service. The repository documents product flows for posts, profiles, messages, invitations, highlights, settings, location discovery, and recommendations rather than a single isolated demo.',
    sections: [
      { heading: 'One Flutter product surface', paragraphs: ['The client is organised as a Flutter application, allowing the same widget and navigation model to serve supported platforms. The repository includes native platform directories, but the product behaviour remains centred in Dart.', 'That structure is valuable for a social product with many connected screens: profile changes, location selection, messaging, and post interactions can share models and presentation patterns instead of being reimplemented per platform.'], media: { type: 'image', src: '/images/pulse/home-screen.png', alt: 'Pulse feed screen', caption: 'The Flutter client brings feed and interaction flows into one application.' } },
      { heading: 'Route-focused backend services', paragraphs: ['The TypeScript backend separates routes for authentication, posts, profiles, messages, settings, invitations, activity, highlights, and pulses. Firebase and Firebase Admin modules provide the shared service boundary, while a dedicated realtime module handles live interaction concerns.', 'This route-level separation makes the public implementation auditable: each product capability has a named entry point rather than disappearing into one large server file. Compiled output is present alongside the TypeScript source, making source/build hygiene an important next step.'] },
      { heading: 'Location and geohash migration', paragraphs: ['Location discovery is a first-class concern in the repository. A geolocation service, Google Places integration, geohash migration notes, a backfill script, and map-facing client UI show how location data moves from input to indexed discovery.', 'The migration files are especially useful evidence because they record a data-model transition rather than only the final state. Backfilling existing records is part of shipping a new location representation safely.'], media: { type: 'image', src: '/images/pulse/map-page.png', alt: 'Pulse map discovery screen', caption: 'Map discovery is backed by explicit geolocation and geohash services.' } },
      { heading: 'Recommendation service boundary', paragraphs: ['A Python ML service lives under the backend with its own Dockerfile, requirements, deployment helper, and usage documentation. Keeping it separate from request/response routes allows recommendation logic to evolve without forcing the Flutter client to know how scores are produced.', 'The repository therefore exposes three clear layers: the Dart product interface, TypeScript application services, and Python recommendation service. Their contracts deserve the same attention as their internal implementations.'], media: { type: 'video', src: '/images/pulse/PulseDemo.mp4', alt: 'Pulse application demonstration', caption: 'The product combines social, messaging, and discovery interactions.' } },
    ],
    lessons: ['Polyglot systems need explicit boundaries more than they need shared implementation languages', 'Data migrations and backfills are product features when discovery depends on them', 'Separating recommendation infrastructure keeps model work independent from the client'],
    future: ['Remove committed credentials and rotate any exposed service keys', 'Keep generated backend output out of source-focused commits', 'Add contract tests between Flutter models, TypeScript routes, and recommendation responses'],
  },
  'gpu-ray-tracer': {
    slug: 'gpu-ray-tracer', readingTime: '7 min read',
    intro: 'Raytracing-GPU is a compact CUDA renderer implemented in main.cu with reusable headers for vectors, rays, cameras, hittable objects, materials, spheres, and object lists. It writes rendered pixels to PPM output and keeps the complete host/device path visible in a small codebase.',
    sections: [
      { heading: 'Pixels mapped to CUDA work', paragraphs: ['The host program allocates the framebuffer and CUDA random states, configures launch dimensions, invokes scene and render kernels, and copies the finished pixels back for image output. The renderer maps image work onto a two-dimensional CUDA launch rather than hiding execution behind an engine.', 'This direct structure makes the cost model easy to study: allocation, kernel launch, synchronization, and transfer are all explicit.'] },
      { heading: 'A device-side scene model', paragraphs: ['Geometry and material behaviour are split into headers such as sphere.h, material.h, hitable.h, and hitable_list.h. Camera rays, intersection records, and scattering logic are available to CUDA device code, allowing each thread to trace its own samples.', 'The design favours clarity over a complex acceleration structure. A hittable list provides a straightforward scene traversal and establishes the object model needed for future spatial indexing.'], media: [{ type: 'image', src: '/images/raytracer/raytracing.webp', alt: 'Output from the CUDA ray tracer', caption: 'CUDA threads evaluate camera rays and material interactions.' }, { type: 'image', src: '/images/raytracer/cornell.png', alt: 'Rendered Cornell-style scene', caption: 'PPM output provides a simple, inspectable render target.' }] },
      { heading: 'Independent random sampling', paragraphs: ['The project uses cuRAND state so parallel render work can draw random samples without sharing one serialized generator. Randomness supports antialiasing and material scattering, both of which require many independent decisions across pixels.', 'Per-thread state is a practical GPU concern: correctness depends not only on the rendering equation but also on avoiding accidental correlation and unsafe shared mutation.'] },
      { heading: 'What the repository proves', paragraphs: ['The public code verifies a CUDA render pipeline, scene abstraction, camera, sphere intersections, materials, and file output. It does not include benchmark records or an implemented BVH, so the portfolio presents those as future work rather than completed performance claims.', 'That distinction makes the project stronger: the implemented path is concrete, and the next optimisation questions are clear.'] },
    ],
    lessons: ['A small renderer is ideal for seeing host/device responsibilities without framework noise', 'Parallel random sampling requires explicit state design', 'Performance claims should follow profiling evidence, not the presence of CUDA alone'],
    future: ['Add reproducible CPU/GPU benchmarks', 'Introduce a GPU-appropriate acceleration structure', 'Replace committed binaries and generated renders with release artifacts'],
  },
  'vulkan-rendering-engine': {
    slug: 'vulkan-rendering-engine', readingTime: '7 min read',
    intro: 'Vulkan-Programming is a focused Windows/C++ Vulkan exercise. Its public source is concentrated in a Visual Studio project, a main.cpp implementation, and compiled vertex and fragment shader artifacts, making it a useful record of explicit graphics setup without claiming a larger engine than the repository contains.',
    sections: [
      { heading: 'Owning Vulkan setup', paragraphs: ['The application source works directly with Vulkan’s explicit object model. Instance, device, queue, surface, swapchain, image, render-pass, pipeline, command, and synchronization responsibilities are visible to the application rather than delegated to a high-level renderer.', 'That verbosity is the learning objective: resource lifetimes and setup order become concrete, and failures can be traced to a specific API boundary.'] },
      { heading: 'Shaders as build artifacts', paragraphs: ['The repository contains SPIR-V vertex and fragment shader files under the project shader directory. Vulkan consumes these compiled modules as part of pipeline creation, so shader compilation is a separate build concern from C++ compilation.', 'Keeping the artifact boundary visible helps explain why pipeline state is prepared ahead of drawing instead of assembled implicitly on every frame.'] },
      { heading: 'Presentation and synchronization', paragraphs: ['A Vulkan frame depends on image acquisition, command submission, and presentation happening in a valid order. The exercise exposes the semaphores and fences needed to coordinate that work.', 'Even in a small application, swapchain resources are tied to the window surface and must be treated as a group. This is one of the clearest lessons Vulkan offers about explicit ownership.'] },
      { heading: 'Repository scope', paragraphs: ['The public project is an early graphics exercise rather than a feature-complete rendering engine. Visual Studio build output is committed beside the source, while the implementation itself is centred in one main file.', 'Presenting that scope accurately keeps the deep dive useful: it documents the Vulkan concepts exercised and identifies modularisation, asset handling, and reproducible shader builds as the next engineering steps.'] },
    ],
    lessons: ['Vulkan makes resource ownership and synchronization application responsibilities', 'Compiled shaders and pipeline setup belong in the build architecture', 'A focused exercise should be described by the API paths it proves, not by unimplemented engine features'],
    future: ['Split setup into lifetime-safe renderer components', 'Add source shaders and a reproducible SPIR-V compilation step', 'Move IDE and binary output to ignored build directories'],
  },
  'software-ray-caster': {
    slug: 'software-ray-caster', readingTime: '7 min read',
    intro: 'RayCaster is a C software-rendering project concentrated in Raycaster.c with a set of bitmap and PPM texture atlases. It builds a first-person view without a 3D graphics API, which makes every projection, collision, and texture decision inspectable in application code.',
    sections: [
      { heading: 'A grid becomes a 3D view', paragraphs: ['The renderer treats the world as a two-dimensional map and casts viewing rays across the screen. Wall-hit distance determines projected height, turning grid intersections into vertical slices of a first-person scene.', 'This is a deliberately constrained rendering model. It trades arbitrary geometry for a fast and understandable path from map cells to pixels.'], media: { type: 'image', src: '/images/raycaster/raycaster.png', alt: 'RayCaster first-person view', caption: 'A software-rendered scene produced from a grid map and texture data.' } },
      { heading: 'DDA traversal and projection', paragraphs: ['Digital Differential Analyzer traversal advances through grid boundaries rather than taking tiny floating-point steps. The method determines which cell is entered next and stops when the ray reaches a wall.', 'Using distance relative to the camera plane keeps the projection visually straight. The implementation demonstrates how camera geometry and map traversal meet in the inner render loop.'] },
      { heading: 'Texture and sprite assets', paragraphs: ['The Textures directory contains source atlases for walls, sky, sprites, title, win, and loss screens in BMP and PPM forms. These assets show that the project includes a presentation and game-state layer as well as wall projection.', 'Texture coordinates are derived from the wall hit and sampled while drawing each vertical strip. Sprite imagery adds scene elements that are not part of the wall grid.'], media: { type: 'image', src: '/images/raycaster/scaryenemy.png', alt: 'Sprite displayed in the software ray caster', caption: 'Sprite assets are composed with the wall-rendering pass.' } },
      { heading: 'A single-file implementation', paragraphs: ['Keeping the renderer and game flow together makes the prototype easy to follow, but it also couples input, simulation, asset loading, and drawing. The repository includes Windows build output beside source and textures.', 'The next refinement is structural rather than cosmetic: split the renderer, world model, platform layer, and assets so each can be tested and changed independently.'] },
    ],
    lessons: ['A constrained world model can make real-time software rendering practical', 'Projection bugs are often geometry problems rather than syntax problems', 'Asset handling and game states are part of a renderer once it becomes an experience'],
    future: ['Separate platform, renderer, and world modules', 'Document controls and the texture-atlas format', 'Add frame-time measurements and reproducible builds'],
  },
  'rust-systems-lab': {
    slug: 'rust-systems-lab', readingTime: '6 min read',
    intro: 'Rust-Programming is a collection of game-development experiments rather than a million-line systems laboratory. The clearest source-backed project in the repository is an Amethyst Pong implementation organised around Rust modules and ECS-style systems.',
    sections: [
      { heading: 'Repository as an experiment archive', paragraphs: ['The repository contains multiple self-contained Rust project directories, including framework starter code and generated build trees. This makes it evidence of broad experimentation, but not one cohesive Cargo workspace.', 'The portfolio therefore focuses on the source that can be inspected directly and treats generated target output as repository hygiene to improve.'] },
      { heading: 'Amethyst Pong structure', paragraphs: ['The Amethyst project separates startup state in main.rs and pong.rs from systems for ball movement, paddle input, collision response, and winning conditions. Configuration files hold display and input bindings.', 'This system-oriented structure is the technical centre of the project. Behaviour is decomposed by responsibility and scheduled over shared game state rather than concentrated in one update function.'] },
      { heading: 'ECS as a design constraint', paragraphs: ['Entity-component-system architecture encourages data and behaviour to be modelled separately. Paddles, balls, transforms, and scores become composable state, while focused systems query and update the parts they need.', 'For a small Pong game this may look elaborate, but it reveals how an engine architecture scales beyond one object hierarchy. It also makes ordering between movement, collision, and scoring an explicit concern.'] },
      { heading: 'What should be cleaned next', paragraphs: ['Large target directories and dependency artifacts dominate the public repository. They prove local builds happened, but they obscure authored source and make Git history harder to review.', 'A curated set of source-only examples, each with a short README and lockfile policy, would turn the experiment archive into a much stronger learning record.'] },
    ],
    lessons: ['Repository structure should distinguish authored experiments from generated dependencies', 'ECS systems make game-update responsibilities and ordering explicit', 'Accurate scope is more credible than counting generated code as authored work'],
    future: ['Remove target directories and generated dependencies from version control', 'Curate the strongest experiments into documented source-only projects', 'Add tests for scoring and collision edge cases'],
  },
  'hospital-management-platform': {
    slug: 'hospital-management-platform', readingTime: '8 min read',
    intro: 'Hospital Management Platform is a deployed Next.js application with dedicated patient, doctor, staff, and administrator workflows. Its repository exposes the full product surface: appointment routes, role-specific pages, Prisma migrations, test-result delivery, two-factor flows, reminders, and communication integrations.',
    sections: [
      { heading: 'Roles shape the application', paragraphs: ['Patient, doctor, staff, and administrator experiences have separate pages and API routes rather than one dashboard with hidden controls. Doctor appointment, patient, profile, and test views sit beside patient booking, records, and authentication flows.', 'This route structure makes responsibilities visible, but real security still depends on server-side authorization at every data boundary. The distinction between a role-specific UI and an enforced permission is central to this kind of system.'], media: { type: 'video', src: '/images/hospitaldatabase/2025-07-13 21-59-32.mp4', alt: 'Hospital Management Platform role-based workflow', caption: 'Separate product surfaces support patient, clinician, staff, and administrator tasks.' } },
      { heading: 'Relational workflow data', paragraphs: ['Prisma migrations record the evolution of appointments, doctor and patient profiles, services, contact details, preferences, staff access, two-factor fields, and test results. These are connected workflow entities rather than a single unstructured profile document.', 'The migration history is valuable technical evidence: it shows the schema changing as appointment notes, duration, priority, contacts, and clinical-result requirements emerged.'] },
      { heading: 'Authentication is several flows', paragraphs: ['The API tree includes password login, registration, logout, current-user lookup, doctor and staff login, authenticator setup, SMS code delivery, and multiple verification routes. Password hashing and JWT packages are part of the stack.', 'Having focused routes makes each flow easier to find, but it also increases the need for shared validation, rate limiting, consistent session rules, and tests that prevent role crossover.'] },
      { heading: 'Notifications and result delivery', paragraphs: ['Appointment reminders, email setup, SMS integrations, and downloadable patient test-result routes connect stored data to real user communication. A PDF route turns a structured result into a patient-facing document.', 'These integrations make operational failure part of the product: retries, provider configuration, audit history, and safe error messages matter alongside the happy path.'] },
    ],
    lessons: ['Role-specific navigation must be backed by per-request authorization', 'Migration history documents how real workflow requirements reshape data', 'Notification and document delivery need explicit failure handling'],
    future: ['Centralise and test authorization policies for every role-sensitive query', 'Add integration tests for appointments, 2FA, reminders, and result downloads', 'Document secrets management and production provider configuration'],
  },
  'biology-challenge-site': {
    slug: 'biology-challenge-site', readingTime: '6 min read',
    intro: 'Biology Challenge is a Next.js educational site whose repository combines subject imagery, custom page components, theme support, and reusable Radix-based UI. The strongest implementation detail is not a backend claim but the way visual biology content is assembled into an interactive web experience.',
    sections: [
      { heading: 'An App Router composition', paragraphs: ['The source contains a root layout, landing and home routes, a profile route, header, image-section components, and a theme provider. Shared UI primitives for buttons, cards, dialogs, dropdowns, avatars, and scrolling support the page-level composition.', 'This separation keeps the subject-specific pieces focused while common interactions remain reusable and accessible.'], media: { type: 'image', src: '/images/biologywebsite/biology-website.png', alt: 'Biology Challenge interface', caption: 'Subject imagery and reusable components form the main experience.' } },
      { heading: 'Content-led visual structure', paragraphs: ['Biology imagery is stored with the application and composed through image-focused components. The public tree includes fossil, predation, herd, and supporting visual assets, showing that the experience is built around concrete educational media rather than decorative placeholders.', 'The challenge is maintaining readable hierarchy around visually strong material. Image sections need captions, meaningful alternative text, predictable cropping, and responsive layouts.'], media: { type: 'image', src: '/images/biologywebsite/aboutus.png', alt: 'Biology Challenge profile or about section', caption: 'Profile and supporting pages reuse the site’s component vocabulary.' } },
      { heading: 'Theme and interaction primitives', paragraphs: ['A theme button and provider establish light/dark presentation at the application level. Radix-backed components provide behaviour for dialogs, dropdowns, scrolling, and other controls, while Tailwind handles the visual layer.', 'Using primitives narrows the amount of interaction code that must be invented locally and gives custom presentation a stronger accessibility baseline.'] },
      { heading: 'From showcase to learning product', paragraphs: ['The repository verifies a polished educational website, but it does not expose a complete challenge engine, assessment model, or progress backend. Those should remain future product work rather than implied current features.', 'The next useful step is to connect the strong presentation layer to structured learning content and measurable learner state.'] },
    ],
    lessons: ['Concrete subject media creates a stronger educational identity than generic decoration', 'Reusable interaction primitives reduce accessibility risk', 'A visual showcase and an assessment product should be described as different scopes'],
    future: ['Add structured challenge content with accessible answer feedback', 'Provide reduced-motion and robust image-caption treatment', 'Introduce persisted learner progress only with a proper backend'],
  },
  'pico-drone-controller': {
    slug: 'pico-drone-controller', readingTime: '7 min read',
    intro: 'Drone-Main is Raspberry Pi Pico firmware that combines a BNO055 orientation sensor, NRF24L01 radio input, and reusable PID controller code. Its public source shows the control-loop integration and Pico SDK build rather than a complete production flight stack.',
    sections: [
      { heading: 'Sensor bring-up', paragraphs: ['The project includes BNO055 C/C++ support and initialises orientation sensing for the Pico application. Calibration and Euler orientation data provide roll, pitch, and heading inputs to the controller.', 'Sensor bring-up is part of control correctness. Mode selection, calibration state, bus communication, and units all need to be known before gains have any meaning.'] },
      { heading: 'Independent PID axes', paragraphs: ['PID_v1.cpp and its header implement reusable proportional, integral, and derivative behaviour. The main application creates separate control paths for roll, pitch, and yaw and feeds them measured orientation and requested setpoints.', 'Separate axes are easy to inspect and tune initially, while also exposing the limitation that a real airframe couples those motions. Output limits and sample timing are as important as the three gains.'] },
      { heading: 'Radio input and loop integration', paragraphs: ['NRF24L01 input brings pilot commands into the loop. The main C++ file coordinates joystick values, IMU readings, controller calculations, and serial output within one embedded application.', 'This is the project’s strongest engineering evidence: several hardware-facing libraries are composed into one deterministic control path under the Pico SDK.'], media: { type: 'image', src: '/images/robotics/vex.jpg', alt: 'Embedded robotics hardware', caption: 'The firmware work sits at the boundary between sensors, radio control, and actuators.' } },
      { heading: 'Safety boundary', paragraphs: ['The repository shows control calculations and downstream output, but it should not be presented as a verified autonomous flight controller. Motor mixing, arming, radio-loss behaviour, watchdogs, and hardware-in-the-loop validation are safety-critical next steps.', 'Making that boundary explicit is part of responsible embedded documentation.'] },
    ],
    lessons: ['Control gains are inseparable from sensor quality and sample timing', 'Hardware integrations benefit from focused drivers and one readable main loop', 'Flight-control prototypes need explicit safety and validation boundaries'],
    future: ['Add arming, watchdog, radio-loss, and output failsafes', 'Implement and bench-test motor mixing', 'Record timestamped telemetry for repeatable gain tuning'],
  },
  'networked-mastermind': {
    slug: 'networked-mastermind', readingTime: '7 min read',
    intro: 'Mastermind is an A Level Computer Science project built in GameMaker. The repository contains maker, breaker, client, server, and single-player controllers; rooms and assets; save/load objects; scoring feedback; and a MultiClient extension for network communication.',
    sections: [
      { heading: 'Rules as controller state', paragraphs: ['GameMaker objects coordinate peg selection, row progression, guess submission, validation feedback, and terminal win/loss states. Separate colour and slot objects provide the board pieces while controller events own transitions.', 'This object/event model suits a turn-based game because input, validation, and drawing happen at well-defined moments instead of one continuous simulation loop.'], media: { type: 'video', src: '/images/mastermind/2025-01-27 22-23-07.mp4', alt: 'Networked Mastermind gameplay', caption: 'A complete maker-and-breaker game flow built in GameMaker.' } },
      { heading: 'Maker, breaker, and network roles', paragraphs: ['Dedicated maker and client/server controller objects make the hidden-code roles explicit. The MultiClient extension includes platform-specific post-run helpers and supports messages that coordinate peers.', 'For a turn-based game, exchanging role and outcome state is more appropriate than attempting to synchronize rendering every frame. The network protocol should still document message shapes and failure behaviour.'] },
      { heading: 'Scoring duplicate colours', paragraphs: ['Mastermind scoring must distinguish exact-position matches from correct colours in the wrong position without counting one peg twice. The validation controller is therefore more than a UI concern: it is the rules engine for each submitted row.', 'This is a strong candidate for isolated tests because duplicate-colour combinations are easy to reason about incorrectly through manual play alone.'] },
      { heading: 'A complete submission surface', paragraphs: ['Rooms, sprites, audio, UI controls, data files, save/load objects, and single-player support make the repository a complete coursework game rather than only a networking proof of concept.', 'The next refinement is reproducibility: document controls, protocol assumptions, and build steps so another person can run the project without reverse-engineering the GameMaker object tree.'] },
    ],
    lessons: ['Turn-based games benefit from explicit state transitions', 'Network messages should communicate game facts rather than rendering state', 'Duplicate-colour scoring deserves isolated tests'],
    future: ['Add automated cases for duplicate-colour scoring', 'Document network messages, ports, and reconnect behaviour', 'Publish a clean build guide and release artifact'],
  },
  'minecraft-mod-prototype': {
    slug: 'minecraft-mod-prototype', readingTime: '5 min read',
    intro: 'testmod is an early Java modding repository with a Gradle build, Forge-oriented development configuration, and a Blockbench model asset. Most of its large public footprint is generated Minecraft build output, so this deep dive focuses only on the authored project structure that can be verified.',
    sections: [
      { heading: 'Working inside a host runtime', paragraphs: ['Minecraft mod development starts from the host application’s lifecycle, mappings, registries, and build conventions. The Gradle project and launch configuration establish that environment before custom content can run.', 'This is a useful lesson in extension engineering: the application controls startup and rendering, while the mod connects at supported registration and event boundaries.'], media: { type: 'image', src: '/images/minecraftmod/minecraft.png', alt: 'Minecraft mod prototype running in game', caption: 'Custom content is tested inside the Forge development runtime.' } },
      { heading: 'From Blockbench to game asset', paragraphs: ['The bbmodels directory contains a Blockbench model. A model only becomes game content after export, resource placement, naming, registration, and association with behaviour.', 'That pipeline joins visual authoring to Java runtime code and makes asset conventions part of the programming interface.'], media: { type: 'image', src: '/images/minecraftmod/mcdim.png', alt: 'Custom Minecraft environment from the prototype', caption: 'The prototype explores the path from authored assets to in-game presentation.' } },
      { heading: 'Generated output versus authored source', paragraphs: ['The repository commits a very large build tree containing transformed and compiled Minecraft classes. Those files are tool output, not authored project implementation, and they make the meaningful mod code difficult to review.', 'Accurate portfolio treatment means not using that generated size as a project metric. A clean ignore policy and source-only history would make the actual contribution much clearer.'] },
      { heading: 'Prototype scope', paragraphs: ['The public project proves familiarity with the Gradle/Forge development environment and model pipeline. It does not currently provide a clear feature README, packaged release, or clean source tree.', 'The best next step is curation: isolate the mod entry points and resources, explain the gameplay feature, and publish a reproducible release.'] },
    ],
    lessons: ['Host applications dictate extension lifecycle and build constraints', 'Asset naming and registration are executable parts of a game pipeline', 'Generated dependencies should never be presented as authored code'],
    future: ['Remove generated build and Minecraft class output from Git history', 'Document the implemented content and registration path', 'Publish a source-focused Forge project and playable release'],
  },
}
